const String baseUrl = "https://qaqnuz.herokuapp.com";
const String registerUrl ="$baseUrl/accounts/register";
const String loginUrl ="$baseUrl/accounts/login";
const String refreshUrl ="$baseUrl/accounts/refresh";
const String logoutUrl ="$baseUrl/accounts/logout";
const String profileUrl ="$baseUrl/accounts/profile";
const String mapUrl ="$baseUrl/accounts/search";
const String storesUrl ="$baseUrl/stores";
const String wishListUrl ="$baseUrl/accounts/wishlist";
const String apartmentUrl ="$baseUrl/apartments";
const String productUrl ="$baseUrl/products";
const String vehicleUrl ="$baseUrl/vehicles";
const String wishlistUrl ="$baseUrl/accounts/wishlist";
const String changePasswordUrl ="$baseUrl/accounts/changePassword";
const String resentVerificationUrl ="$baseUrl/accounts/verify/resend";
const String chatUrl ="wss://qaqnuz.herokuapp.com?roomId=";
const String getAllChatUrl ="$baseUrl/chats";
